version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    command: bash -c "gunicorn main:app --bind 0.0.0.0:8030 --worker-class aiohttp.GunicornWebWorker --access-logfile '-' --log-level debug --reload"
    volumes:
      - ./src:/app
    ports:
      - 8040:8030
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
      - redis
  
  db:
    image: mongo:4.4.5-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sample_user
      - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - 27018:27017
