FROM python:3.8-slim

ENV PYTHONUNBUFFERED 1

ENV TZ=Asia/Dhaka

WORKDIR /app

RUN apt-get update && apt-get install build-essential curl -y
RUN pip3 install -U pip

ADD requirements-dev.txt /app

RUN pip3 install -r requirements-dev.txt && \
    apt-get --purge autoremove build-essential -y

COPY src/ /app/

EXPOSE 8030
